(define (make-account ini pw)
  (let ((password pw) (wrongtime 0)) 
    (define (withdraw amount)
        (if (>= ini amount)
          (begin (set! ini (- ini amount))
                 ini)
          "Insufficient funds"))
    (define (deposit amount)
        (begin (set! ini (+ ini amount))
                ini))

    (define (wrong yang) 
      (if (>= 6 wrongtime) 
        (begin (set! wrongtime (+ wrongtime 1)) 
        "Incorrect password!!!")
        ;wrongtime)
         (call-the-cops)
         ))
      (define (call-the-cops) "Dial 911")

  (define (dispatch n m)
    (if (eq? n password) 
      (begin (set! wrongtime 0)
            (cond ((eq? m 'withdraw) withdraw)
                  ((eq? m 'deposit) deposit)
                  (else (error "Unknown request -- MAKE-ACCOUNT"
                                   m))))
      wrong))
  ;(if(not (null? pw)) (dispatch) "There is no password")))
  dispatch))

;(define acc (make-account 100 'sec))
(define acc (make-account 100 'secret-password))
